// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDarLq8W2evBUvj4g9bCwLSItFQIQLmru4',
    appId: '1:292806550582:android:ba2755bd1603d4aaf02497',
    messagingSenderId: '292806550582',
    projectId: 'coockleen2',
    storageBucket: 'coockleen2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWF5UxweG4fdlryHy4wKfi2zIHCHkL84',
    appId: '1:292806550582:ios:89341a39b4025170f02497',
    messagingSenderId: '292806550582',
    projectId: 'coockleen2',
    storageBucket: 'coockleen2.appspot.com',
    iosClientId: '292806550582-r0p7i73bd4at4c068aq5dbhc1ont6bb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.coocklen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWF5UxweG4fdlryHy4wKfi2zIHCHkL84',
    appId: '1:292806550582:ios:5bb7e7cc3edba2aff02497',
    messagingSenderId: '292806550582',
    projectId: 'coockleen2',
    storageBucket: 'coockleen2.appspot.com',
    iosClientId: '292806550582-6n5k31m6vjhc78evrcum2qdv9u01fsro.apps.googleusercontent.com',
    iosBundleId: 'com.example.coocklen.RunnerTests',
  );
}
